POST http://localhost:3000/login
Content-Type: application/json

{"username":"georg","password":"urxn"}

###

GET http://localhost:3000/sse
Accept: text/event-stream

GET http://localhost:3000/jukebox

###
GET http://localhost:3000/jukebox/js/script.js
###
GET http://localhost:4000/jukebox/jukebox_allefiles.txt
###
GET https://graf.priv.at/~suck/alldirs.txt
